language: go

go:
  - 1.12.2

env:
  - DEP_VERSION="0.5.1"

go_import_path: github.com/lvnacapital/algorand

before_install:
  # dep : Download the binary to bin folder in $GOPATH and make the binary executable
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

  # gox:
  - go get -u github.com/mitchellh/gox

  # golint
  - go get -u golang.org/x/lint/golint

install:
  - dep ensure

script:
  - make -r all
