dist: xenial
language: go
go:
  - 1.12.x
  - master
cache: false
env:
  global:
    - DEP_VERSION=0.5.1
    - ALGORAND_HOST=127.0.0.1
    - ALGOD_PORT=8080
    - KMD_PORT=7833
    - ALGOD_TOKEN=374de74fa794248762e5a
    - KMD_TOKEN=be84aa55f61665645ed68
    - CLOUDFRONT_DISTRIBUTION_ID=E1Q1GNVQ0NNUN2
go_import_path: github.com/lvnacapital/algorand
before_install:
  - python3 --version
  - pip --version
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o ${GOPATH}/bin/dep
  - chmod +x ${GOPATH}/bin/dep
  - go get -u github.com/mitchellh/gox
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/sqs/goreturns
  - pip install awscli --upgrade --user
install:
  - dep ensure
script:
  - make -r all
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
    #secure: ddBDCHzkk+A9x3pYOb0TynuWeiDC4yLkEtZ5KYU9+zqPk5i4jqgzpnSJXTom/WrZJMnEAjcXWUOnlSNMEzHroZSuxVpl9fRs5xQP9Mt74b11uMAfDWS4UWFFb/Z6dE9FxiE2tb5M+Wgye6t2AH+8Lic9joWIV8XQ5leJ3hwzSy1WJk7FKWXlMtD7qvZLg8LBMd8pxmu5y5t52+Oi/ZxphQCaRiDBpTYMqom7TSg4MT4R0b5Udtn5cYNOuB3bKi3KmAa23m9p6xE+5LYTzl7PLgGrxQ3F270ymmPMgVGjra2Z2iXZTmcn/PJlVyHJkL5OGZrQ+IRpaJn8lKr58sZjr71bzQXkzRvQlwQozirIEUws4VzBC2R3g/8OfeJJoGbLNczZE9wUe2q+yKWGe6GjXTSGtQnJNbxsrzcHQdKilf1/4GnPZ0YsK0yDmFIxc+fqT90BS7aZ5YnGgGdF9ArzfF1xP6dNwSN0XUmegtvtW4MVHgy+QQvsLSqbBP6Q9s3mlSIPOTe3gLGccvtgGp2pLNAjqIuwTH4yI97yZZ+7Ix+QNXEDRF9EZ7vzOXUvJTF+c7zC2khWcr3Jh5HoRWi4miyzuavEQGE2jRncWJJfH2SsrCLaTWNQupHXN+KYaVh6LFb5Fp3s3o/wcdX+cas6IyubByUZp+XDS0OAHGRrpIE=
  bucket: lvnacapital
  local-dir: build
  upload-dir: algorand
  acl: public_read
  region: us-west-2
  skip_cleanup: true
  detect_encoding: false
  #default_text_charset: utf-8
  cache_control: no-cache
  dot_match: true
  #endpoint: https://sfo2.digitaloceanspaces.com
  on:
    repo: lvnacapital/algorand-go
    branch: master
    go: 1.12.x
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = 'master' && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /algorand
